name: Flutter Dart Building

on:
  push:
  
env:
  FLUTTER_VERSION: '3.19.3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Flutter SDK 
        uses: hughware/flutter-action@v1.0.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-key: flutter-sdk-${{ runner.os }}-${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
      - run: flutter pub get

      - name: Build for Android
        run: flutter build apk 
       
      - name: Upload Artifact for Android
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/app-release.apk
